#!/bin/bash
. /opt/remotepi/etc/config.sh

# Generate teh asterisk bits
sudo chown asterisk:devuan /opt/remotepi/etc/asterisk
sudo chmod g+wx /opt/remotepi/etc/asterisk
sudo rm -f /opt/remotepi/etc/asterisk/pjsip_wizard_remotepi.conf
cat > /opt/remotepi/etc/asterisk/pjsip_wizard_remotepi.conf <<EOF
[radio0]
type = wizard
max_contacts = 4
accepts_auth = yes
accepts_registrations = yes
has_phoneprov = no
transport = transport-udp
has_hint = yes
hint_exten = 0
inbound_auth/username = ${UA_USER}
inbound_auth/password = ${UA_PASS}
;endpoint/allow = g722,opus,gsm,ulaw,alaw
endpoint/allow = g722
endpoint/context = ${UA_CONTEXT}
EOF
sudo rm -f /opt/remotepi/etc/asterisk/extensions_remotepi.conf

sudo mkdir -p /opt/remotepi/etc/ssl/
sudo cp /etc/letsencrypt/live/istabpeople.com/*.pem /opt/remotepi/etc/ssl/
sudo chown -R asterisk:asterisk /opt/remotepi/etc/ssl/
sudo chmod o-rwx /opt/remotepi/etc/ssl

sudo service asterisk restart
