#!/bin/bash
. /opt/remotepi/etc/config.sh

# Generate teh asterisk bits
cat > /tmp/install.out <<EOF
[guest]
type=aor
max_contacts=5
remove_existing=yes
  
[guest]
type=auth
auth_type=userpass
username=guest
password=guest
 
[guest]
type=endpoint
aors=guest
auth=guest
dtls_auto_generate_cert=yes
webrtc=yes
context=guest
disallow=all
use_avpf=yes
;allow=opus,speex,g722,ulaw,gsm
allow=speex,g722,ulaw,gsm

[mobile]
type=aor
max_contacts=1
remove_existing=yes
  
[mobile]
type=auth
auth_type=userpass
username=${ADMIN_USER}
password=${ADMIN_PASS}
 
[mobile]
type=endpoint
aors=mobile
auth=mobile
dtls_auto_generate_cert=yes
webrtc=yes
context=mobile
disallow=all
;allow=opus,speex,g722,ulaw,gsm
allow=g722,speex,gsm,ulaw,alaw

[radio0]
type=aor
max_contacts=1
remove_existing=yes
  
[radio0]
type=auth
auth_type=userpass
username=${UA_USER}
password=${UA_PASS}
 
[radio0]
type=endpoint
transport=transport-udp
aors=radio0
auth=radio0
dtls_auto_generate_cert=yes
webrtc=yes
context=radio0
disallow=all
;allow=opus,speex,g722,ulaw,gsm
;allow=g722
allow=g722
EOF
sudo mv /tmp/install.out /opt/remotepi/etc/asterisk/pjsip.remotepi.conf
cat > /tmp/install.out <<EOF
[mobile]
type=friend
host=dynamic
regexten=301
secret=1234567890
context=mobile
permit=10.0.0.0/255.0.0.0
EOF
sudo mv /tmp/install.out /opt/remotepi/etc/asterisk/iax.remotepi.conf

cat > /tmp/install.out  <<EOF
[remotepi]
type = user
read_only = no
password = remotepi
EOF
sudo mv /tmp/install.out /opt/remotepi/etc/asterisk/ari.remotepi.conf

cat > /tmp/install.out  <<EOF
;;;;;;;;;;;;;;;
; ft891 radio ;
;;;;;;;;;;;;;;;
[radio0]
exten => 0,1,NoOp()
 same => n,Set(VOLUME(TX)=4)
 same => n,Stasis(remotepi,\${CONTEXT})

[readbackfreq]
exten => 1,1,Noop()
 same => n,Verbose(Speaking \${SAY_DATA})
 same => n,Espeak("Frequency \${SAY_DATA}",any)
 same => n,WaitExten()
; same => n,Hangup()

[mobile]
; Ham-radio stuff
exten => 5000,1,Goto(ham-menu,s,1)
include => common

[ham-login]
; Do we need to login?
exten => s,1,Noop()
exten => s,n,Goto(ham-login,1,1)

; Read and check password
exten => 1,1,Authenticate($HAM_PASS)
 same => n,Goto(ham-menu,s,1)
 same => n,Hangup()
exten => t,1,Hangup()

[ham-menu]
exten => *,1,Playback(conf-unmuted)
 same => n,Goto(ham-menu,s,3)
exten => #,1,Playback(conf-muted)
 same => n,Goto(ham-menu,s,3)

; Listen
exten => 0,1,NoOp()
 same => n,Stasis(remotepi,\${CONTEXT})
 same => n,Hangup()

;;; User requests logout
exten => 8,1,Playback(goodbye)
 same => n,,Hangup()
exten => 9,1,Goto(hhux-out,s,1)

;;; User didn't enter anything
exten => t,1,Goto(ham-menu,s,3)
exten => i,1,Playback(invalid)
 same => n,Goto(ham-menu,s,2)

exten => s,1,Answer()
; 1 = LISTEN, 2 = MODE, 3 = FREQ, * = MUTE, # = UNMUTE, 9 = HHO
 same => n,Playback(extension)
 same => n,WaitExten(3)

[guest]
exten => 0,1,NoOp()
 same => n,Stasis(remotepi,guest)

; Ham-radio stuff
exten => 5000,1,Goto(ham-menu,s,1)
include => common
EOF
sudo mv /tmp/install.out /opt/remotepi/etc/asterisk/extensions.remotepi.conf

[ -d "/etc/letsencrypt/live/${LETSENCRYPT_DOMAIN}/" ] && {
   echo "==> Mirroring letsencrypt certificates for: asterisk"
   sudo mkdir -p /opt/remotepi/etc/ssl/
   sudo cp /etc/letsencrypt/live/${LETSENCRYPT_DOMAIN}/*.pem /opt/remotepi/etc/ssl/
   sudo chown -R ${ASTERISK_HOST_USER}:$root /opt/remotepi/etc/ssl/
   sudo chmod go-rwx /opt/remotepi/etc/ssl
}
sudo chown -R ${ASTERISK_HOST_USER}:root /opt/remotepi/etc/asterisk
sudo service asterisk restart
