#!/bin/bash
. /opt/remotepi/etc/config.sh

echo "<sip:${UA_USER}@127.0.0.1>;transport=udp;auth_pass=${UA_PASS};answermode=early" > ${UA_DIR}/accounts
cat > ${UA_DIR}/config <<EOF
#
# baresip configuration -- example for linux
#

#------------------------------------------------------------------------------

# Core
poll_method		epoll		# poll, select, epoll ..

# SIP
sip_listen		0.0.0.0:${UA_PORT}
#sip_certificate	cert.pem
#sip_cafile		ca.crt

# Call
call_local_timeout	20
call_max_calls		1

# Audio
audio_buffer        	200     	# ms
#audio_path		/usr/local/share/baresip
audio_player		${AU_OUTDEV}
audio_source		${AU_INDEV}
#audio_alert		${AU_ALERTDEV}
ausrc_srate		48000
auplay_srate		48000
ausrc_channels		1
auplay_channels		1
#audio_txmode		poll		# poll, thread
audio_level		no
ausrc_format		s16		# s16, float, ..
auplay_format		s16		# s16, float, ..
auenc_format		s16		# s16, float, ..
audec_format		s16		# s16, float, ..

# Video
#video_source		v4l2,/dev/video0
#video_display		x11,nil
video_size		352x288
video_bitrate		512000
video_fps		25.00
video_fullscreen	no
videnc_format		yuv420p

# AVT - Audio/Video Transport
rtp_tos			184
#rtp_ports		10000-20000
#rtp_bandwidth		512-1024 # [kbit/s]
rtcp_mux		no
jitter_buffer_delay	5-10		# frames
rtp_stats		no
#rtp_timeout		60

# Network
#dns_server		1.1.1.1:53
#dns_server		1.0.0.1:53
#net_interface		wlan1

#------------------------------------------------------------------------------
# Modules

module_path		/usr/lib/baresip/modules

# UI Modules
module			stdio.so
module			cons.so
module			evdev.so
#module			httpd.so

# Audio codec Modules (in order)
#module			opus.so
#module			amr.so
#module			g7221.so
module			g722.so
#module			g726.so
#module			g711.so
#module			gsm.so
#module			l16.so

# Audio filter Modules (in encoding order)
#module			vumeter.so
#module			sndfile.so
#module			speex_pp.so
#module			plc.so
#module			webrtc_aec.so

# Audio driver Modules
module			alsa.so
#module			portaudio.so

# Video codec Modules (in order)
#module			avcodec.so
#module			vp8.so
#module			vp9.so

# Video filter Modules (in encoding order)
#module			selfview.so

# Video source modules
module			v4l2.so
#module			avformat.so
#module			x11grab.so
#module			cairo.so

# Video display modules
#module			x11.so
#module			sdl.so

# Audio/Video source modules
#module			rst.so
#module			gst.so
#module			gst_video.so

# Compatibility modules
#module			ebuacip.so

# Media NAT modules
#module			stun.so
#module			turn.so
#module			ice.so
#module			natpmp.so
#module			pcp.so

# Media encryption modules
#module			srtp.so
#module			dtls_srtp.so


#------------------------------------------------------------------------------
# Temporary Modules (loaded then unloaded)

module_tmp		uuid.so
module_tmp		account.so


#------------------------------------------------------------------------------
# Application Modules

module_app		auloop.so
#module_app		b2bua.so
module_app		contact.so
module_app		debug_cmd.so
#module_app		echo.so
#module_app		gtk.so
module_app		menu.so
#module_app		mwi.so
#module_app		presence.so
module_app		syslog.so
#module_app		mqtt.so
#module_app		ctrl_tcp.so
module_app		vidloop.so


#------------------------------------------------------------------------------
# Module parameters


# UI Modules parameters
cons_listen		127.0.0.1:5555 # cons - Console UI UDP/TCP sockets

#http_listen		0.0.0.0:8000 # httpd - HTTP Server

ctrl_tcp_listen		127.0.0.1:4444 # ctrl_tcp - TCP interface JSON

evdev_device		/dev/input/event0

# Opus codec parameters
opus_bitrate		28000 # 6000-510000
#opus_stereo		yes
#opus_sprop_stereo	yes
#opus_cbr		no
#opus_inbandfec		no
#opus_dtx		no
#opus_mirror		no
#opus_complexity	10
#opus_application	audio	# {voip,audio}
#opus_samplerate	48000
#opus_packet_loss	10	# 0-100 percent (expected packet loss)

#jack_connect_ports	yes

# Selfview
video_selfview		window # {window,pip}
#selfview_size		64x64

# ZRTP
#zrtp_hash		no  # Disable SDP zrtp-hash (not recommended)

# Menu
#menu_bell		yes
#redial_attempts	0 # Num or <inf>
#redial_delay		5 # Delay in seconds
#ringback_disabled	no
#statmode_default	off
#menu_clean_number	no

# GTK
#gtk_clean_number	no

# avcodec
#avcodec_h264enc	libx264
#avcodec_h264dec	h264
#avcodec_h265enc	libx265
#avcodec_h265dec	hevc
#avcodec_hwaccel	videotoolbox

# MQTT
#mqtt_broker_host	sollentuna.example.com
#mqtt_broker_port	1883
#mqtt_broker_clientid	baresip01 # Has to be unique for each client, defaults to "baresip"
#mqtt_broker_user	alfred
#mqtt_broker_password	Crocus
#mqtt_basetopic		baresip/01 # May be uniqe for each client you want to control. Defaults to "baresip"

# sndfile
#snd_path		/tmp

# EBU ACIP
#ebuacip_jb_type     	fixed   # auto,fixed

config
contacts
current_contact
uuid
EOF

echo "baresip -f /opt/remotepi/etc/baresip-${UA_CHAN}/ -e \"/dial ${CONF_EXTEN}@127.0.0.1\"" > ${RUN}/baresip-launch.sh
chmod 0755 ${RUN}/baresip-launch.sh
